name = "lustre_websocket"
version = "0.7.5"
target = "javascript"

licences = ["MIT"]
description = "Web Socket requests from lustre"
repository = { type = "codeberg", user = "kero", repo = "lustre_websocket" }
links = [
    { title = "Package", href = "https://hex.pm/packages/lustre_websocket" },
]
dev-dependencies = { gleeunit = "~> 1.0"}

[dependencies]
gleam_stdlib = "~> 0.32 or ~> 1.0"
lustre = "~> 3.0 or ~> 4.0"
